"""
Scan a bv-export --target directory for trip folders, for bv-web's
trip-list/trip-detail pages.

Deliberately doesn't touch blackvue.archive/blackvue.trip at all -
those model the *source* recordings bv-export reads from, before a
trip even exists as a folder. This module only ever looks at
bv-export's own *output*: the folders it already wrote under
--target, one per trip, each holding whatever combination of
front.mp4/rear.mp4/stitch.mp4/map.mp4/... a given `bv-export` run
happened to produce (see export/trip_export.py). A trip folder is
identified by containing trip.log - the one file export_trip() always
writes first (see export/trip_log.py) - so this can't mistake an
unrelated directory (e.g. the --map-cache-dir's .osm_cache) for a
trip.

Copyright (C) 2026 Christer R. (sssreh)

SPDX-License-Identifier: GPL-3.0-or-later
"""

from __future__ import annotations

import re
import time
from dataclasses import dataclass
from dataclasses import field
from dataclasses import replace
from pathlib import Path
from xml.etree import ElementTree as ET

from ..core.camera_config import CameraConfigError
from ..core.camera_config import config_path
from ..core.camera_config import list_camera_ids
from ..core.camera_config import load_camera_config

TRIP_LOG_FILENAME = "trip.log"

# Matches gpx_writer.write_gpx()'s own namespace (export/gpx_writer.py)
# - a module-private constant there, so redefined here rather than
# imported, to avoid pulling in a whole extra module dependency for
# one string.
_GPX_NAMESPACE = "http://www.topografix.com/GPX/1/1"

# Matches TripLog's own header line, e.g.
# "=== bv-export trip log: trip_20260715_133458_20260715_141235 ==="
# - see export/trip_log.py's __init__(). Read straight from the log
# rather than re-derived from the folder name, since the folder name
# may carry an extra --prefix (folder_name_for_trip()) that isn't
# part of the trip's own label.
_TRIP_LABEL_RE = re.compile(r"^=== bv-export trip log: (.+) ===$")

# The video files export_trip() may have written, in the order
# they're preferred for playback: stitch.mp4 already has everything
# composited together, so it wins over the raw front/rear feeds when
# it exists.
VIDEO_FILENAMES = ("stitch.mp4", "front.mp4", "rear.mp4")
MAP_FILENAME = "map.mp4"
# Track-up static map (task #795, Christer: "I think we should have
# different names for track up and not, then we always get the
# correct map") - a distinct file from MAP_FILENAME so a trip exported
# once with --map-track-up and once without can show/serve both,
# rather than the second run's file silently replacing the first's.
# See export/trip_export.py's own map_track_up docstring paragraph for
# the render-side half of this.
MAP_TU_FILENAME = "map_tu.mp4"
GSENSOR_VIDEO_FILENAME = "gsensor.mp4"
GPX_FILENAME = "trip.gpx"
SRT_FILENAME = "trip.srt"
# trip_info.txt (export/trip_info.py) - a short plain-text trip
# summary (duration, distance/speed, start/end address) written on
# every export, unconditionally. Christer: "are trip summary still
# there" - it was already written to every trip folder, just never
# surfaced anywhere in bv-web's own UI (only known_filenames'd like
# gpx/srt below, so it could be downloaded but not read at a glance).
TRIP_INFO_FILENAME = "trip_info.txt"
# trip_summary.txt (export/trip_export.py's `trip_summary=True` path,
# generate.scene.summarize_trip()) - a genuine AI-written narrative of
# the trip ("how conditions changed" over the drive), synthesized from
# this trip's own recordings' scene descriptions. Only written when
# --trip-summary was passed (needs 2+ already-described recordings),
# unlike TRIP_INFO_FILENAME above which is unconditional - so this
# gets its own bool field rather than folding into `trip_info`.
# Confusingly, the *existing* `trip_summary` property on TripAssets
# below parses TRIP_INFO_FILENAME, not this file - that property
# predates this one and its name is now misleading, but renaming it
# would break every existing trip_detail.html reference for no
# functional gain, so the new field/property here are named
# `trip_narrative`/`trip_narrative_text` instead to avoid a second
# collision. Christer: "yes do that for trip summary too" (asking for
# Read-aloud on this file, after being told it's generated by
# --trip-summary but never surfaced in bv-web at all).
TRIP_SUMMARY_FILENAME = "trip_summary.txt"


@dataclass(frozen=True)
class TripAssets:
    """Which of a trip folder's possible files actually exist on
    disk - a real bv-export run only produces the subset its flags
    asked for (e.g. no map.mp4 without --map, no gsensor.mp4 without
    --gsensor-video), so every field here can legitimately be empty/
    None.

    `map_video`/`map_video_tu` can both be set at once (task #795) -
    a trip re-exported with the opposite --map-track-up setting writes
    its own distinct file (map.mp4 vs map_tu.mp4) rather than
    overwriting the other, so both can coexist and both are surfaced
    here. `map_zoom_videos` doesn't need a matching `_tu` field of its
    own - it's already a glob-built tuple (folder.glob("map_zoom_*.mp4")
    in scan_trip() below), which picks up map_zoom_60m_tu.mp4 right
    alongside map_zoom_60m.mp4 with no extra code, the two
    distinguished from each other only by their filename text."""

    folder: Path
    # The URL-safe identifier bv-web uses for this trip. Set
    # explicitly by scan_trip()/scan_all_trips() rather than derived
    # here as folder.name - a trip found under a specific camera's own
    # Target directory (see scan_all_trips()'s own docstring) needs an
    # id like "Kirby/trip_..." to stay unique across cameras and to
    # resolve back through that camera's config; folder.name alone
    # would only ever be the last path component.
    id: str
    label: str
    videos: tuple[str, ...] = field(default_factory=tuple)
    map_video: str | None = None
    map_video_tu: str | None = None
    map_zoom_videos: tuple[str, ...] = field(default_factory=tuple)
    gsensor_video: str | None = None
    gpx: bool = False
    srt: bool = False
    trip_info: bool = False
    trip_narrative: bool = False

    @property
    def trip_summary(self) -> list[tuple[str, str]]:
        """(label, value) pairs parsed from trip_info.txt (export/
        trip_info.py) - the short plain-text trip summary (duration,
        distance/speed, moving/idle time, start/end address, Parking
        footage flag, total size) bv-export writes unconditionally on
        every run. Christer: "are trip summary still there" - it was,
        just never surfaced anywhere in bv-web's own UI before this;
        trip_detail.html renders these pairs directly instead of
        making someone go find the file on disk.

        Computed live from trip_info.txt on every access (same
        "reads already-written files, doesn't generate anything new"
        convention as ArchiveRecording.scene_summary on the archive-
        browser side) rather than cached on the dataclass, since
        TripAssets instances themselves are cached by TripCache and a
        stale in-memory copy of the file's *contents* would be a worse
        bug than the small repeated read cost.

        Each trip_info.txt line is "Label: value" (write_trip_info()'s
        own format, always one value per line, never multi-line) so a
        single partition(": ") per line is enough to parse it -
        deliberately not a stricter format (JSON, key=value) since
        this file is meant to be human-readable on its own too, opened
        directly off a NAS share.

        Empty if trip_info.txt doesn't exist (e.g. a trip folder from
        a bv-export build that predates task #124) or can't be read
        for any reason - degrades quietly, like every other optional
        per-trip asset here, rather than 500ing the trip detail page
        over a summary file that was always secondary to the video
        itself."""

        if not self.trip_info:
            return []
        try:
            text = (self.folder / TRIP_INFO_FILENAME).read_text(encoding="utf-8")
        except OSError:
            return []
        pairs = []
        for line in text.splitlines():
            if not line.strip():
                continue
            label, sep, value = line.partition(": ")
            pairs.append((label, value) if sep else (line, ""))
        return pairs

    @property
    def trip_narrative_text(self) -> str | None:
        """The AI-written trip_summary.txt narrative (see
        TRIP_SUMMARY_FILENAME's own comment above for why this isn't
        named `trip_summary_text` - that name is already taken by the
        unrelated trip_info.txt-backed property above), or None if
        this trip wasn't exported with --trip-summary (or the file
        can't be read).

        Unlike `trip_summary` above, this is real prose - a short
        synthesis of how conditions changed over the drive, not
        structured label/value stats - so trip_detail.html renders it
        as a paragraph with its own Read-aloud button, reusing the
        same `.scene-text`/`.speak-btn` markup and shared TTS script
        the archive recording detail page already uses (see
        base.html's own comment on that script for why it lives
        there, not duplicated per-template).

        Same "read fresh from disk on every access, never cached on
        the dataclass" reasoning as `trip_summary` above."""

        if not self.trip_narrative:
            return None
        try:
            text = (self.folder / TRIP_SUMMARY_FILENAME).read_text(encoding="utf-8")
        except OSError:
            return None
        return text.strip() or None

    @property
    def primary_video(self) -> str | None:
        """The single best video to play for this trip, or None if
        the trip has no video at all (e.g. a GPS-only export with
        neither --stitch nor raw video kept)."""

        return self.videos[0] if self.videos else None

    @property
    def prefix(self) -> str | None:
        """The --prefix bv-export was given for this trip, or None if
        it was exported without one.

        folder_name_for_trip() (export/trip_export.py) always builds
        the folder name as either just `label` or `f"{prefix}_{label}"`
        - never anything else - so the prefix is recovered by
        stripping the trailing "_{label}" off the folder name, the
        same label already read straight from trip.log rather than
        re-derived from the folder name (see the module docstring and
        _TRIP_LABEL_RE above). Nothing before "--prefix" surfaced this
        anywhere in bv-web: the folder name (trip.id) is the only
        place it's visible, and nobody reads raw folder names off a
        NAS share day to day."""

        suffix = f"_{self.label}"
        folder_name = self.folder.name
        if folder_name == self.label:
            return None
        if folder_name.endswith(suffix):
            return folder_name[: -len(suffix)] or None
        return None

    @property
    def known_filenames(self) -> frozenset[str]:
        """Every filename trip_file() is allowed to serve for this
        trip - the web app's file-serving route checks against this
        rather than trusting a filename straight from the URL, so a
        request can't walk outside what was actually found on disk
        here."""

        names = set(self.videos) | set(self.map_zoom_videos)
        if self.map_video:
            names.add(self.map_video)
        if self.map_video_tu:
            names.add(self.map_video_tu)
        if self.gsensor_video:
            names.add(self.gsensor_video)
        if self.gpx:
            names.add(GPX_FILENAME)
        if self.srt:
            names.add(SRT_FILENAME)
        if self.trip_info:
            names.add(TRIP_INFO_FILENAME)
        if self.trip_narrative:
            names.add(TRIP_SUMMARY_FILENAME)
        return frozenset(names)


def _read_trip_label(trip_log_path: Path) -> str | None:
    try:
        with trip_log_path.open("r", encoding="utf-8") as file:
            first_line = file.readline().strip()
    except OSError:
        return None

    match = _TRIP_LABEL_RE.match(first_line)
    return match.group(1) if match else None


def first_gpx_point(path: Path) -> tuple[float, float] | None:
    """Return the (latitude, longitude) of `path`'s first GPX
    trackpoint, or None if the file is missing, unparseable, or has
    no trackpoints at all.

    trip.gpx is written by gpx_writer.write_gpx(), which only ever
    emits a `<trkpt>` for a fix that was already valid with a real
    position (see that function's own docstring) - unlike a raw .gps
    sidecar, where archive_browser.first_valid_gps_fix() has to scan
    past invalid fixes itself, the very first trkpt here already *is*
    the trip's start location, no further filtering needed.
    """

    try:
        root = ET.parse(path).getroot()
    except (OSError, ET.ParseError):
        return None

    trkpt = root.find(f".//{{{_GPX_NAMESPACE}}}trkpt")
    if trkpt is None:
        return None

    try:
        return float(trkpt.attrib["lat"]), float(trkpt.attrib["lon"])
    except (KeyError, ValueError):
        return None


def scan_trip(folder: Path, *, id_: str | None = None) -> TripAssets | None:
    """Return the TripAssets for `folder`, or None if it doesn't look
    like a trip folder (no trip.log).

    `id_` defaults to `folder.name` (the common case: `folder` sits
    directly under a --target directory) - pass it explicitly when the
    returned TripAssets.id needs to be something else, e.g. the full
    "CameraId/trip_..." id scan_all_trips() prefixes trips with, so
    it can be found again through that camera's own config rather
    than just by trailing folder name."""

    trip_log_path = folder / TRIP_LOG_FILENAME
    if not trip_log_path.is_file():
        return None

    label = _read_trip_label(trip_log_path) or folder.name

    videos = tuple(
        name for name in VIDEO_FILENAMES if (folder / name).is_file()
    )
    map_zoom_videos = tuple(
        sorted(path.name for path in folder.glob("map_zoom_*.mp4"))
    )

    return TripAssets(
        folder=folder,
        id=id_ if id_ is not None else folder.name,
        label=label,
        videos=videos,
        map_video=MAP_FILENAME if (folder / MAP_FILENAME).is_file() else None,
        map_video_tu=(
            MAP_TU_FILENAME if (folder / MAP_TU_FILENAME).is_file() else None
        ),
        map_zoom_videos=map_zoom_videos,
        gsensor_video=(
            GSENSOR_VIDEO_FILENAME
            if (folder / GSENSOR_VIDEO_FILENAME).is_file()
            else None
        ),
        gpx=(folder / GPX_FILENAME).is_file(),
        srt=(folder / SRT_FILENAME).is_file(),
        trip_info=(folder / TRIP_INFO_FILENAME).is_file(),
        trip_narrative=(folder / TRIP_SUMMARY_FILENAME).is_file(),
    )


def scan_trips(target: Path) -> list[TripAssets]:
    """Scan `target` (a bv-export --target directory) for trips,
    newest first - every immediate subfolder of `target` that looks
    like a trip (has trip.log), flat, one level only. A `target` that
    doesn't exist yet (e.g. bv-export hasn't been run) is read as zero
    trips rather than an error - bv-web's trip list should just look
    empty, not crash.

    Deliberately flat: a camera-id-nested layout
    (`.../trips/<camera-id>/<trip>`) is scan_all_trips()'s job to
    combine, not this function's - see that function's own
    docstring for why a single flat scan isn't enough to see every
    camera's trips, and why the two used to be conflated here (one
    level of recursion into non-trip subfolders) before that existed.
    Kept flat and single-purpose so a two-segment trip id has exactly
    one meaning app-wide (see app.py's _find_trip()): "camera_id/
    trip_folder", resolved through that camera's own config, never
    "arbitrary subfolder/trip_folder" guessed by walking the
    filesystem."""

    if not target.is_dir():
        return []

    trips = []
    for entry in sorted(target.iterdir()):
        if not entry.is_dir():
            continue
        trip = scan_trip(entry)
        if trip is not None:
            trips.append(trip)

    trips.sort(key=lambda trip: trip.label, reverse=True)
    return trips


def scan_all_trips(config_dir: Path, fallback_target: Path) -> list[TripAssets]:
    """Scan every configured camera's own Target directory for trips,
    plus `fallback_target` (bv-web's own positional TARGET argument),
    combined into one newest-first list.

    Each camera set up via bv-config may have its own Target directory
    (CameraConfig.target, the same value bv-export --target defaults
    to for that camera - see core/camera_config.py) - and nothing
    requires every camera to share one. Reading only `fallback_target`
    (the old, pre-task-762 behavior) meant bv-web only ever saw
    whichever single directory happened to be passed to `bv-web
    serve`, silently missing any camera exporting somewhere else.

    Trips found under a camera's own Target are re-identified as
    "<camera-id>/<trip-id>" (see TripAssets.id's own docstring) so
    they resolve back through that camera's config rather than being
    looked up under `fallback_target` - a trip whose folder name
    happens to collide with one from another camera (a realistic
    scenario: trip folder names are timestamp-derived) still stays
    unambiguous, since the id carries which camera it came from.

    `fallback_target` is still scanned flat, unprefixed - the
    "no camera config at all, just point bv-web straight at a shared
    export directory" case documented in docs/DEPLOY.md's own example
    pipeline, and the landing spot for anything exported with an
    explicit `bv-export --target` override that doesn't match any
    camera's own configured default (see that flag's own "you're on
    your own trip" warning in bv_export.py) - bv-web still shows it,
    just without a camera prefix, exactly as before this function
    existed.

    A trip folder is only ever listed once even if it's reachable
    both ways (e.g. a camera's Target literally *is*
    `fallback_target`) - deduped by each trip's resolved absolute
    folder path."""

    seen_folders: set[Path] = set()
    trips: list[TripAssets] = []

    for camera_id in list_camera_ids(config_dir):
        try:
            config = load_camera_config(config_path(config_dir, camera_id))
        except CameraConfigError:
            continue
        if config.target is None:
            continue
        for trip in scan_trips(config.target):
            folder = trip.folder.resolve()
            if folder in seen_folders:
                continue
            seen_folders.add(folder)
            trips.append(replace(trip, id=f"{camera_id}/{trip.id}"))

    for trip in scan_trips(fallback_target):
        folder = trip.folder.resolve()
        if folder in seen_folders:
            continue
        seen_folders.add(folder)
        trips.append(trip)

    trips.sort(key=lambda trip: trip.label, reverse=True)
    return trips


class TripCache:
    """Caches scan_trip() results briefly, per trip id.

    Exists for one specific request pattern: a video player issues an
    HTTP range request for every chunk it fetches while seeking or
    buffering - many per second during active playback - and every
    one of those hits app.py's trip_file() route, which resolves the
    same trip_id via _find_trip() on every single call. scan_trip()
    itself does several stat()/open() calls (trip.log, up to
    three video filenames, a map_zoom_*.mp4 glob, map/gsensor/gpx/
    srt checks) against the trip's own folder - cheap in
    isolation, but repeated identically on every range request in a
    burst adds up to real, felt latency, especially against a
    Synology bind-mounted volume where each syscall can cost more
    than on a plain local disk.

    A short TTL collapses a whole burst of range requests from one
    seek/buffer event into a single real scan_trip() call, while
    still refreshing often enough that create_app()'s own documented
    promise - a trip bv-export finishes writing while bv-web is
    already running shows up without a restart - still holds: the
    TTL only ever adds a few seconds of staleness, never a restart
    requirement. Deliberately scoped to the single-trip lookup
    _find_trip() uses (trip_detail()/trip_file()), not scan_trips()'s
    full trip-list scan - the trip list is loaded once per page view,
    not once per range request, so it has nothing comparable to
    collapse and is left exactly as fresh as before.
    """

    def __init__(self, ttl_seconds: float = 2.0) -> None:
        self._ttl_seconds = ttl_seconds
        self._entries: dict[str, tuple[TripAssets, float]] = {}

    def get(
        self, target: Path, relative_path: str, *, id_: str | None = None
    ) -> TripAssets | None:
        """Same result as scan_trip(target / relative_path), but
        reused from cache if it was resolved within the last
        ttl_seconds.

        `id_` defaults to `relative_path` (the common flat-target
        case) - pass it explicitly when the two differ, as they do
        for a trip resolved through its own camera's Target directory
        (see app.py's _find_trip()): `relative_path` is just the trip
        folder's own name relative to *that camera's* target, but
        `id_` is the full "camera_id/trip_folder" id the rest of
        bv-web knows it by. Caching keyed on `id_` rather than
        `relative_path` matters here - two different cameras'
        trip folders can share the same timestamp-derived name, and
        without this they'd collide in the cache and one camera's
        trip would occasionally serve up the other's."""

        trip_id = id_ if id_ is not None else relative_path
        now = time.monotonic()

        cached = self._entries.get(trip_id)
        if cached is not None:
            trip, expires_at = cached
            if now < expires_at:
                return trip

        trip = scan_trip(target / relative_path, id_=trip_id)
        if trip is not None:
            self._entries[trip_id] = (trip, now + self._ttl_seconds)
        else:
            # Don't cache a miss - a trip that doesn't exist yet (a
            # typo'd id, or a bv-export run that hasn't started
            # writing trip.log yet) should be re-checked on the very
            # next request, not held as "not found" for the TTL.
            self._entries.pop(trip_id, None)
        return trip
