"""
Synthetic "parking footage skipped" transition clip for bv-export's
--include-parking option.

By default (--include-parking not given), a Parking-mode recording
strictly in the middle of a trip - flanked by other recordings on
both sides, see trip_export.py's _is_mid_trip_parking() - is left out
of front.mp4/rear.mp4/audio.aac and replaced by a short synthetic
clip instead: a still frame reading "PARKING FOOTAGE SKIPPED" for the
video assets, and matching silence for the audio asset, both exactly
PARKING_TRANSITION_DURATION_SECONDS long. Christer asked for the
audio to swap in matching silence too ("keeps stitch.mp4's audio in
sync"), so every substituted asset for the same recording has to
share that one duration.

The clip can't be a single static video file shipped once and reused
everywhere, because ffmpeg's concat demuxer (media.py's
concatenate_media()) stream-copies rather than re-encodes - every
source has to already match its neighbours' own resolution/frame
rate (video) or sample rate/channel layout/codec (audio) exactly,
and those vary by camera/archive. render_parking_transition_video()/
render_parking_transition_silence() below probe whichever real asset
they're standing in for and encode a placeholder to match it, and
ParkingTransitionCache reuses each rendered clip for the rest of the
trip whenever a later skipped recording happens to need the exact
same (width, height, frame_rate) or (codec, sample_rate, channels)
combination.

The still image itself (dark background, red "no parking" icon,
caption) is generated by render_parking_transition_image() below, or
supplied by Christer via --parking-transition-image - the same
"bundled default, overridable with your own picture" convention
--map-icon/--stitch-mirror-icon already use. It's deliberately an
image, not a pre-made video, so render_parking_transition_video() can
always encode it to match whatever resolution/frame rate this trip's
cameras happen to be running at, rather than needing to also match a
fixed frame rate baked into a pre-encoded override clip.

Copyright (C) 2026 Christer R. (sssreh)

SPDX-License-Identifier: GPL-3.0-or-later
"""

from __future__ import annotations

import json
import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

from PIL import Image
from PIL import ImageDraw
from PIL import ImageFont

from ..generate.media import MediaToolError
from ..generate.mp4_box_reader import read_mp4_info
from .media import encode_with_nvenc_fallback

# Christer: "a 3 second video ... that clearly shows that we skip
# parking video". Not exposed as a flag - a fixed, well-known
# duration keeps every substituted recording's video/audio pair
# trivially in sync with each other (see the module docstring).
PARKING_TRANSITION_DURATION_SECONDS = 3.0

_ASSETS_DIR = Path(__file__).parent / "assets"

# Christer's own six Kling-generated "no parking" clips (confirmed his
# own AI-generated content, not third-party footage) - bv-export's CLI
# picks one at random per trip when --parking-transition-random is
# given (and neither --parking-transition-image nor
# --parking-transition-clip is), see bv_export.py's main(). This was
# briefly the *default* behaviour whenever none of those three flags
# was given ("I want them to be randomly inserted if not specified"),
# but Christer later reconsidered that call ("do you think i was
# carried away") and asked to make it opt-in instead - a personal
# export tool showing a different one of his own clips each run,
# unannounced, isn't the kind of predictable behaviour a default
# should have. export_trip() itself still defaults to the plain
# procedural frame when nothing at all is given, and bv_export()'s own
# default now matches that exactly rather than diverging from it, same
# "CLI has its own opinionated default, library stays neutral" split
# already used for --map-icon/--stitch-mirror-icon - see
# map_video.DEFAULT_MAP_ICON_PATH's own comment.
DEFAULT_PARKING_TRANSITION_CLIPS = (
    _ASSETS_DIR / "no_parking_1.mp4",
    _ASSETS_DIR / "no_parking_2.mp4",
    _ASSETS_DIR / "no_parking_3.mp4",
    _ASSETS_DIR / "no_parking_4.mp4",
    _ASSETS_DIR / "no_parking_5.mp4",
    _ASSETS_DIR / "no_parking_6.mp4",
)

# The full pool bv-export's CLI draws its random per-trip pick from:
# Christer's own six clips above, plus `None` standing in for the plain
# procedural frame render_parking_transition_image() draws itself -
# Christer: "I think your clip should be in there to[o]", asking for the
# built-in placeholder to stay reachable by chance alongside his own six,
# not just via an explicit opt-out. `None` is exactly the sentinel
# render_parking_transition_video()/ParkingTransitionCache already treat
# as "no clip, no image - draw the plain procedural frame", so handing
# `random.choice()`'s result straight through as `parking_transition_clip`
# needs no special-casing at all when it happens to land on `None`. Every
# one of the 7 entries has an equal 1-in-7 chance.
RANDOM_PARKING_TRANSITION_POOL = DEFAULT_PARKING_TRANSITION_CLIPS + (None,)

BACKGROUND_COLOR = (20, 20, 20)
# Same red accent used throughout the rest of bv-export's own
# rendering (map_render.py's ROUTE_COLOR/POSITION_DOT_COLOR/
# MARKER_FILL_COLOR are all this same (230, 57, 70)) - a consistent
# "this is bv-export's own overlay" accent color rather than a new
# one invented just for this feature.
ICON_COLOR = (230, 57, 70)
TEXT_COLOR = (255, 255, 255)

# Christer: "would it be possible to get correct å, ä and ö characters"
# (Swedish a-ring/a-umlaut/o-umlaut) - the two candidates below used to
# be the *only* candidates, and both are unreliable: the first is a
# Linux-only system path (absent on Christer's Windows machine, and
# Dockerfile.cli's ffmpeg-only apt install never puts a font package
# there either), and the second only resolves if a same-named file
# happens to already sit in the current working directory. When both
# fail, ImageFont.truetype() raises OSError for every candidate and
# the code fell through to ImageFont.load_default() - a tiny built-in
# bitmap font confirmed (by direct rendering test) to have no
# Swedish-letter glyphs at all, so they rendered as blank/tofu boxes.
# The bundled copy is tried first and is expected to always resolve
# from a real install (see pyproject.toml's package-data entry for
# assets/*.ttf); the two old paths stay afterwards purely as a
# best-effort fallback if the bundled file is ever missing for some
# reason.
_FONT_CANDIDATES = (
    str(_ASSETS_DIR / "DejaVuSans-Bold.ttf"),
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    "DejaVuSans-Bold.ttf",
)

_CACHED_FONT_BY_SIZE: dict[int, "ImageFont.ImageFont"] = {}


def _load_font(size: int) -> "ImageFont.ImageFont":
    if size not in _CACHED_FONT_BY_SIZE:
        for candidate in _FONT_CANDIDATES:
            try:
                _CACHED_FONT_BY_SIZE[size] = ImageFont.truetype(candidate, size)
                break
            except OSError:
                continue
        else:
            _CACHED_FONT_BY_SIZE[size] = ImageFont.load_default()

    return _CACHED_FONT_BY_SIZE[size]


def render_parking_transition_image(width: int, height: int) -> Image.Image:
    """Draw bv-export's default "parking footage skipped" frame: a
    dark background, a red "prohibited" icon (circle + diagonal
    slash, the same shape as a real "No Parking" road sign), and a
    caption underneath - sized proportionally to `width`/`height` so
    it reads clearly at any camera resolution.

    Deliberately no letter inside the circle (an early version drew a
    "P", but the slash cut across its stem in a way that read as an
    "R" instead) - the caption text below already spells out
    "parking" in full, so the icon only needs to carry "prohibited".
    """

    image = Image.new("RGB", (width, height), BACKGROUND_COLOR)
    draw = ImageDraw.Draw(image)

    short_side = min(width, height)
    radius = short_side * 0.22
    cx, cy = width / 2, height * 0.42
    stroke = max(2, round(short_side * 0.028))

    draw.ellipse(
        (cx - radius, cy - radius, cx + radius, cy + radius),
        outline=ICON_COLOR,
        width=stroke,
    )

    slash_radius = radius - stroke / 2
    angle_offset = 0.7071 * slash_radius  # cos(45deg)/sin(45deg) * radius
    draw.line(
        (
            cx - angle_offset, cy - angle_offset,
            cx + angle_offset, cy + angle_offset,
        ),
        fill=ICON_COLOR,
        width=stroke,
    )

    caption_font = _load_font(max(14, round(width * 0.045)))
    draw.multiline_text(
        (width / 2, height * 0.8),
        "PARKING FOOTAGE\nSKIPPED",
        font=caption_font,
        fill=TEXT_COLOR,
        anchor="mm",
        align="center",
        spacing=6,
    )

    return image


def _fit_and_pad_image(image: Image.Image, width: int, height: int) -> Image.Image:
    """Scale `image` to fit within width x height without distorting
    its own aspect ratio, then pad with BACKGROUND_COLOR to exactly
    width x height - used when Christer supplies his own
    --parking-transition-image, which won't generally already match
    this trip's own camera resolution. Same letterbox/pillarbox
    approach stitch.py's _fit_and_pad() uses for the map panel.
    """

    fitted = image.convert("RGB")
    fitted.thumbnail((width, height), Image.LANCZOS)

    canvas = Image.new("RGB", (width, height), BACKGROUND_COLOR)
    offset = ((width - fitted.width) // 2, (height - fitted.height) // 2)
    canvas.paste(fitted, offset)
    return canvas


def probe_video_properties(path: Path) -> tuple[int, int, float, str | None]:
    """Return (width, height, frame_rate, codec) for a video file -
    what render_parking_transition_video() needs to encode a
    placeholder clip that ffmpeg's concat demuxer will accept
    alongside it. `codec` is a normalized "h264"/"hevc" (matching
    ffprobe's own codec_name for the ones this matters for), or None
    if it couldn't be determined - callers then fall back to
    bv-export's original default (H.264), same as before codec
    detection existed.

    Tries ffprobe first; falls back to reading the MP4's own box
    structure directly (mp4_box_reader.read_mp4_info(), the same
    tolerant reader media.py's get_span() already falls back to for
    duration) if ffprobe fails outright, *or* if it exits cleanly but
    hands back an unusable width/height/frame_rate. This isn't a
    rare-corruption edge case for Parking-mode recordings specifically:
    BlackVue's own Parking-mode time-lapse container structure is a
    known quirk that trips ffmpeg's strict STSC/STCO consistency check
    ("contradictionary STSC and STCO", "error reading header") on
    every such file, not just damaged ones - other players (VLC, the
    BlackVue viewer itself) open them fine, so the video data is
    intact even though ffprobe refuses it. A second, quieter variant
    of the same underlying problem: ffprobe can also exit 0 while
    reporting `avg_frame_rate` as "0/0" for these files (it can't
    derive an average from the stream header alone) - no exception at
    all, so this has to be checked explicitly rather than only caught
    via `except`. Falling back here (either way) means a Parking
    recording's own genuinely-intact video can still be probed for a
    placeholder's sizing, rather than every single one always failing
    straight to the "drop this segment" path, or worse, silently
    producing a 0.0 frame rate placeholder (Christer's real-world
    report: "P files still show 1 frame for the duration").

    Codec detection specifically exists for a *third*, more serious
    variant of the same class of bug: even when width/height/frame_rate
    all come back correct, render_parking_transition_video() used to
    always encode the placeholder as H.264 regardless of what the real
    recording actually used. On a real trip from Christer's own 4K
    HEVC camera, that meant an H.264 placeholder got spliced via
    concatenate_media()'s stream-copy concat into a stream declared as
    HEVC - which doesn't error (ffmpeg's concat demuxer doesn't
    validate codec consistency), but produces a file no real decoder
    can parse from the splice point onward ("Invalid NAL unit size",
    the picture frozen while separately-muxed audio keeps playing -
    reproduced directly against a minimal HEVC+H.264 concat fixture
    before this fix, and confirmed clean after matching the codec).
    """

    try:
        result = subprocess.run(
            [
                "ffprobe", "-v", "error",
                "-select_streams", "v:0",
                "-show_entries", "stream=width,height,avg_frame_rate,codec_name",
                "-of", "json",
                str(path),
            ],
            capture_output=True,
            text=True,
            check=True,
        )
    except FileNotFoundError as exc:
        raise MediaToolError("ffprobe not found on PATH") from exc
    except subprocess.CalledProcessError as exc:
        return _probe_video_properties_from_boxes(
            path, f"ffprobe failed for {path.name}: {(exc.stderr or '').strip()}"
        )

    try:
        stream = json.loads(result.stdout)["streams"][0]
        width = int(stream["width"])
        height = int(stream["height"])
        frame_rate = _parse_frame_rate(stream["avg_frame_rate"])
    except (KeyError, IndexError, ValueError) as exc:
        raise MediaToolError(
            f"could not parse ffprobe output for {path.name}"
        ) from exc

    # codec_name is read best-effort, separately from the
    # width/height/frame_rate parse above - an unrecognized or missing
    # codec_name isn't a reason to fail the whole probe (unlike a bad
    # width/height/frame_rate), it just means the caller falls back to
    # the H.264 default, same as every recording had before this
    # existed.
    codec = stream.get("codec_name") if isinstance(stream, dict) else None
    codec = codec if codec in _RECOGNIZED_CODECS else None

    if width <= 0 or height <= 0 or frame_rate <= 0:
        # ffprobe can exit 0 and still hand back a useless
        # avg_frame_rate of "0/0" - seen on a real Parking recording
        # (Christer: "P files still show 1 frame for the duration, it
        # shouldn't even be included by default", a *mid-trip* file,
        # so this was going through the placeholder path, not raw
        # inclusion). "0/0" happens when ffprobe can't derive an
        # average from the stream header it read - a different
        # failure mode than the STSC/STCO error _probe_video_properties_from_boxes()
        # was originally written for (that one makes ffprobe exit
        # non-zero; this one doesn't), but the same fix applies: don't
        # hand render_parking_transition_video() a 0.0 frame rate,
        # fall back to the box reader's own frame_count/duration
        # instead, same as an outright ffprobe failure.
        return _probe_video_properties_from_boxes(
            path,
            f"ffprobe returned an unusable frame rate for {path.name} "
            f"(width={width}, height={height}, "
            f"avg_frame_rate={stream['avg_frame_rate']!r})",
        )

    return width, height, frame_rate, codec


# Recognized ffprobe codec_name values for probe_video_properties()'s
# own codec detection - kept in the same vocabulary
# mp4_box_reader._CODEC_FOURCC_MAP maps its own fourcc readings to, so
# either probing path (ffprobe or the box-reader fallback) hands the
# caller back the same two possible values.
_RECOGNIZED_CODECS = ("h264", "hevc")


def _probe_video_properties_from_boxes(
    path: Path, error_message: str
) -> tuple[int, int, float, str | None]:
    """The probe_video_properties() ffprobe fallback - see that
    function's own docstring. Called both when ffprobe itself fails
    (a `subprocess.CalledProcessError`, e.g. "contradictionary STSC
    and STCO") and when ffprobe exits cleanly but hands back a
    degenerate `avg_frame_rate` of "0/0" - `error_message` is already
    formatted for whichever case applies, and is what gets raised if
    the box reader can't produce a complete (width, height,
    frame_rate) either, since that's still the more informative
    message - it names the real file and ffmpeg's own diagnostic,
    rather than "no tkhd box" or similar.

    `frame_count > 0` (not just "is not None") matters: a real-world
    Parking recording, from Christer's own report, produced a
    placeholder that "only showed 1 frame, but lasted the duration of
    the P file" - traced to a video track whose stsz reported a
    sample_count of exactly 0 (a fragmented-MP4 track stores its real
    per-fragment sample counts in moof/trun boxes this reader doesn't
    parse, not in the top-level stsz table this reader does; stsz's
    own count field just reads back as 0 in that shape, which is a
    legitimate, distinct-from-"unknown" box value, not a sentinel).
    frame_count=0 previously survived this check and produced
    frame_rate=0.0, which render_parking_transition_video() then
    handed to ffmpeg as `-r 0.0` - a degenerate placeholder rather
    than the intended 3-second one, and (per Christer's own second
    symptom, footage missing for a stretch right after) apparently
    also confused the concat demuxer's timeline for whatever followed
    it. Treating 0 the same as missing here means this specific class
    of file falls back to the pre-existing, safe "warn and drop this
    segment" behavior instead of producing a broken placeholder -
    properly reading fragmented MP4 sample counts would need moof/trun
    parsing this reader doesn't have yet.

    `info.codec`, unlike width/height/frame_count, is never required
    for this to return successfully - a Parking recording whose codec
    the box reader couldn't identify still gets a placeholder, just
    encoded as bv-export's H.264 default, exactly like it always was
    before per-recording codec matching existed. Only the STSC/STCO
    class of file (ffprobe fails outright, box reader also can't help)
    was ever "no codec info" in practice, since that's the same file
    the box reader's own stsz/tkhd reads already fail on.
    """

    try:
        info = read_mp4_info(path)
    except MediaToolError:
        info = None

    if (
        info is not None
        and info.width is not None
        and info.height is not None
        and info.frame_count is not None
        and info.frame_count > 0
        and info.duration_seconds > 0
    ):
        return (
            info.width, info.height,
            info.frame_count / info.duration_seconds,
            info.codec,
        )

    raise MediaToolError(error_message)


def probe_audio_properties(path: Path) -> tuple[str, int, int] | None:
    """Return (codec_name, sample_rate, channels) for an audio file's
    first audio stream, or None if it can't be read - a missing/
    unreadable source just means the caller skips substituting
    silence for that one recording rather than aborting the export.
    """

    try:
        result = subprocess.run(
            [
                "ffprobe", "-v", "error",
                "-select_streams", "a:0",
                "-show_entries", "stream=codec_name,sample_rate,channels",
                "-of", "json",
                str(path),
            ],
            capture_output=True,
            text=True,
            check=True,
        )
    except (FileNotFoundError, subprocess.CalledProcessError):
        return None

    try:
        stream = json.loads(result.stdout)["streams"][0]
        return (
            str(stream["codec_name"]),
            int(stream["sample_rate"]),
            int(stream["channels"]),
        )
    except (KeyError, IndexError, ValueError):
        return None


def _parse_frame_rate(value: str) -> float:
    if "/" in value:
        numerator, _, denominator = value.partition("/")
        denominator_value = float(denominator)
        if denominator_value == 0:
            return 0.0
        return float(numerator) / denominator_value
    return float(value)


def render_parking_transition_video(
    destination: Path,
    *,
    width: int,
    height: int,
    frame_rate: float,
    duration_seconds: float = PARKING_TRANSITION_DURATION_SECONDS,
    image_path: Path | None = None,
    clip_path: Path | None = None,
    codec: str = "h264",
) -> None:
    """Render the "parking footage skipped" placeholder video at
    `destination`, sized/timed to match a real recording's own
    width/height/frame_rate - see this module's docstring for why
    that matters for the concat demuxer.

    `codec` ("h264" or "hevc", see media.py's
    encode_with_nvenc_fallback()) should be the same recording's own
    video codec too, for the same reason: concatenate_media()'s
    stream-copy concat needs a byte-compatible splice, not just a
    matching resolution/frame rate - see probe_video_properties()'s
    own docstring for the real-world bug this fixes. Defaults to
    "h264" (bv-export's original, only-ever codec) for any caller that
    doesn't know the source's codec (e.g. it couldn't be detected).

    `clip_path`, if given (Christer's own --parking-transition-clip -
    e.g. one of his own AI-generated "no parking" clips), takes
    priority over `image_path` and is used instead of a still frame:
    scaled/padded to width x height the same way `image_path` is (see
    _render_from_clip()), looped or trimmed to exactly
    `duration_seconds` regardless of its own source length, re-encoded
    to `frame_rate`, and stripped of any audio track entirely - every
    front.mp4/rear.mp4 recording in this whole pipeline is already
    video-only (audio lives in its own separate audio.aac), and
    concatenate_media()'s stream copy needs this placeholder's video
    stream to match its neighbours exactly, which a passenger audio
    track would break.

    Otherwise, `image_path`, if given (Christer's own
    --parking-transition-image picture), is fitted/padded to width x
    height; with neither given, render_parking_transition_image()
    draws the default frame.
    """

    destination.parent.mkdir(parents=True, exist_ok=True)

    if clip_path is not None:
        _render_from_clip(
            clip_path, destination,
            width=width, height=height, frame_rate=frame_rate,
            duration_seconds=duration_seconds, codec=codec,
        )
        return

    if image_path is not None:
        with Image.open(image_path) as source:
            frame = _fit_and_pad_image(source, width, height)
    else:
        frame = render_parking_transition_image(width, height)

    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
        frame_path = Path(tmp.name)
    try:
        frame.save(frame_path)
        encode_with_nvenc_fallback(
            [
                "-loop", "1",
                "-i", str(frame_path),
                "-t", str(duration_seconds),
                "-r", str(frame_rate),
            ],
            destination,
            video_codec=codec,
        )
    finally:
        frame_path.unlink(missing_ok=True)


def _render_from_clip(
    clip_path: Path,
    destination: Path,
    *,
    width: int,
    height: int,
    frame_rate: float,
    duration_seconds: float,
    codec: str = "h264",
) -> None:
    """Re-encode `clip_path` (a real video, not a still image) into
    `destination`: fitted/padded to width x height without distorting
    its own aspect ratio (same scale-then-pad idiom stitch.py's own
    _fit_and_pad() uses for the map panel), looped with -stream_loop
    -1 and cut to exactly `duration_seconds` with -t - handles a
    source shorter *or* longer than `duration_seconds` uniformly,
    since -stream_loop repeats indefinitely and -t (as an output
    option, placed after -i) always wins - re-timed to `frame_rate`,
    and stripped of its own audio track with -an (see
    render_parking_transition_video()'s own docstring for why).

    `codec` - see render_parking_transition_video()'s own docstring;
    threaded through here the same way regardless of whether the
    placeholder's own visual content came from Christer's clip or the
    default procedural frame, since it's about matching the *neighbour
    recordings'* codec, unrelated to which source image/clip was used.

    Since the loop always restarts from `clip_path`'s own frame 0, a
    source longer than `duration_seconds` effectively contributes only
    its own first `duration_seconds` - never a middle or end segment -
    and a source shorter than `duration_seconds` loops back to its own
    start to fill the rest, rather than freezing on its last frame or
    leaving the placeholder short (Christer: "if an external clip is
    added only the first 3 seconds should be imported" - already true
    here for any clip at or above the fixed duration, verified with
    real fixtures both directions).
    """

    encode_with_nvenc_fallback(
        [
            "-stream_loop", "-1",
            "-i", str(clip_path),
            "-t", str(duration_seconds),
            "-r", str(frame_rate),
            "-an",
            "-vf", (
                f"scale=w={width}:h={height}:force_original_aspect_ratio=decrease,"
                f"pad={width}:{height}:(ow-iw)/2:(oh-ih)/2"
            ),
        ],
        destination,
        video_codec=codec,
    )


def render_parking_transition_silence(
    destination: Path,
    *,
    sample_rate: int,
    channels: int,
    duration_seconds: float = PARKING_TRANSITION_DURATION_SECONDS,
) -> None:
    """Render a silent audio clip at `destination`, matching a real
    recording's own sample rate/channel count - see this module's
    docstring for why that matters for the concat demuxer. Always
    encoded as AAC, the same codec extract_audio() produces for every
    real recording's own audio.aac.
    """

    destination.parent.mkdir(parents=True, exist_ok=True)
    channel_layout = "mono" if channels == 1 else "stereo"

    try:
        subprocess.run(
            [
                "ffmpeg", "-y",
                "-f", "lavfi",
                "-i", f"anullsrc=r={sample_rate}:cl={channel_layout}",
                "-t", str(duration_seconds),
                "-c:a", "aac",
                "-ar", str(sample_rate),
                "-ac", str(channels),
                str(destination),
            ],
            capture_output=True,
            text=True,
            check=True,
        )
    except FileNotFoundError as exc:
        raise MediaToolError("ffmpeg not found on PATH") from exc
    except subprocess.CalledProcessError as exc:
        raise MediaToolError(
            f"ffmpeg silence render failed for {destination.name}: "
            f"{exc.stderr.strip()}"
        ) from exc


@dataclass
class ParkingTransitionCache:
    """Renders each distinct video (width, height, frame_rate) or
    audio (codec, sample_rate, channels) placeholder at most once per
    bv-export run, reusing the same file for every later skipped
    Parking recording that happens to need the same combination - a
    trip with several mid-trip Parking recordings at the same camera
    resolution only pays for one real render.

    `work_dir` holds the rendered clips for the lifetime of one
    export_trip() call; the caller is responsible for cleaning it up
    afterwards (trip_export.py uses a tempfile.TemporaryDirectory()).
    """

    work_dir: Path
    image_path: Path | None = None
    clip_path: Path | None = None
    _video_cache: dict[tuple[int, int, float, str], Path] = field(default_factory=dict)
    _silence_cache: dict[tuple[str, int, int], Path] = field(default_factory=dict)
    _next_id: int = 0

    def video_for(self, source: Path, *, fallback_source: Path | None = None) -> Path:
        """Return a placeholder video matching `source`'s own width/
        height/frame_rate/codec, rendering one if this is the first
        request for that combination. `clip_path`, if set, takes
        priority over `image_path` - see render_parking_transition_video().

        Matching `source`'s own codec (falling back to "h264", the
        original always-used default, if it couldn't be determined)
        matters as much as matching width/height/frame_rate - see
        probe_video_properties()'s own docstring for the real-world
        splice corruption this fixes.

        `fallback_source`, if given (trip_export.py passes the sibling
        FRONT/REAR file from the same recording), is probed instead
        whenever `source` itself can't be - e.g. a mid-trip Parking
        recording whose own file is corrupted on the SD card (ffprobe's
        "contradictionary STSC and STCO"/"error reading header").
        Front and rear cameras on the same recording always share
        resolution and frame rate in practice, so this keeps both
        sides' placeholders - and therefore front.mp4/rear.mp4's
        lengths - in sync, instead of only the corrupted side silently
        dropping that segment while its sibling keeps it (Christer
        hit exactly this: both PF and PR happened to fail together
        that time, so it went unnoticed, but a single-sided failure
        would have desynced the two videos from that point on). If
        `fallback_source` also fails to probe, the *original* error
        from `source` is what gets raised/reported, since that's the
        file this placeholder actually stands in for.
        """

        try:
            width, height, frame_rate, codec = probe_video_properties(source)
        except MediaToolError as exc:
            if fallback_source is None:
                raise
            try:
                width, height, frame_rate, codec = probe_video_properties(
                    fallback_source
                )
            except MediaToolError:
                raise exc from None

        codec = codec or "h264"
        key = (width, height, round(frame_rate, 3), codec)

        if key not in self._video_cache:
            self._next_id += 1
            destination = self.work_dir / f"parking_transition_{self._next_id}.mp4"
            render_parking_transition_video(
                destination,
                width=width,
                height=height,
                frame_rate=frame_rate,
                image_path=self.image_path,
                clip_path=self.clip_path,
                codec=codec,
            )
            self._video_cache[key] = destination

        return self._video_cache[key]

    def silence_for(self, source: Path) -> Path | None:
        """Return a silent placeholder audio clip matching `source`'s
        own codec/sample rate/channel count, or None if `source`'s
        audio properties can't be read (see probe_audio_properties())
        - the caller then leaves that recording's audio out entirely,
        same as it always has for any recording missing Asset.AUDIO.
        """

        properties = probe_audio_properties(source)
        if properties is None:
            return None

        codec_name, sample_rate, channels = properties
        key = (codec_name, sample_rate, channels)

        if key not in self._silence_cache:
            self._next_id += 1
            destination = self.work_dir / f"parking_silence_{self._next_id}.aac"
            render_parking_transition_silence(
                destination,
                sample_rate=sample_rate,
                channels=channels,
            )
            self._silence_cache[key] = destination

        return self._silence_cache[key]
