"""
FolderAdapter - the "folder" CameraAdapter.

Real, usable support for a plain folder tree of ordinary video files
(phone clips, GoPro/action-cam footage, anything with no BlackVue-
specific metadata) - not a proof of concept (see manifest.json's own
description and docs/CAMERA_ADAPTERS.md). Unlike BlackVueAdapter, this
isn't a delegation wrapper around existing code: ArchiveReader/
RecordingId.parse() both hard-assume BlackVue's flat "YYYYMMDD_HHMMSS_K"
filename convention (see recording_id.py), which a folder of ordinary
videos simply doesn't have.

The actual recursive-scan/timestamp-resolution/synthesized-RecordingId
logic lives in `adapters/_recursive_scan.py`, shared with GoProAdapter
(both scan a plain recursive folder tree the exact same way - see that
module's own docstring for why the scanning logic was factored out
rather than duplicated once GoProAdapter needed the same thing).
FolderAdapter itself is now just that shared logic plus this
adapter's own manifest and its (unsupported) telemetry/network/config
capability stubs.

STATUS: implemented and registered (see registry.py). Thumbnails
(capabilities.thumbnails == "generated") are NOT generated by this
module - the manifest's own thumbnail_generator code hook is still
queued; a recording with no thumbnail asset degrades the same way an
older/incomplete BlackVue archive already does throughout bv-web
(ArchiveRecording.thumbnail_direction returns None, the grid shows no
image for it) rather than blocking this pass on building that hook
too.
"""

from __future__ import annotations

from pathlib import Path

from ...archive.archive import Archive
from ...archive.recording import Recording
from ...archive.recording_id import RecordingId
from ...core.endpoint import Endpoint
from ...telemetry.gps_reader import GpsFix
from ...telemetry.gsensor_reader import GSensorSample
from .._recursive_scan import find_recording_in_recursive_archive
from .._recursive_scan import scan_recursive_archive
from ..base import AdapterCapabilityError
from ..manifest import load_manifest

_MANIFEST_PATH = Path(__file__).parent / "manifest.json"
_MANIFEST = load_manifest(_MANIFEST_PATH)

# The single kind/direction code manifest.json's kind_vocabulary and
# direction_vocabulary both declare - see module docstring.
_KIND_CODE = "V"


class FolderAdapter:
    """The "folder" CameraAdapter - see module docstring."""

    manifest = _MANIFEST

    def open_archive(self, path: Path) -> Archive:
        return scan_recursive_archive(path, self.manifest, _KIND_CODE)  # type: ignore[return-value]

    def find_recording(self, path: Path, recording_id: RecordingId) -> Recording | None:
        """Resolve a single recording by id - see
        _recursive_scan.find_recording_in_recursive_archive()'s own
        docstring for why this is a full rescan filtered by id rather
        than a targeted lookup."""

        return find_recording_in_recursive_archive(
            path, recording_id, self.manifest, _KIND_CODE
        )

    def read_gps(self, path: Path) -> tuple[GpsFix, ...]:
        raise AdapterCapabilityError(
            f"{self.manifest.adapter_id} adapter's manifest does not "
            "declare gps support"
        )

    def read_gsensor(self, path: Path) -> tuple[GSensorSample, ...]:
        raise AdapterCapabilityError(
            f"{self.manifest.adapter_id} adapter's manifest does not "
            "declare gsensor support"
        )

    def connect(
        self, endpoints: list[Endpoint], timeout: int = 5
    ) -> tuple[Endpoint, object]:
        raise AdapterCapabilityError(
            f"{self.manifest.adapter_id} adapter's manifest does not "
            "declare network_connect support"
        )

    def config_snapshot_seconds(self, config_text: str) -> int:
        raise AdapterCapabilityError(
            f"{self.manifest.adapter_id} adapter's manifest does not "
            "declare config_snapshot support"
        )
