"""
FolderAdapter - the "folder" CameraAdapter.

Real, usable support for a plain folder tree of ordinary video files
(phone clips, GoPro/action-cam footage, anything with no BlackVue-
specific metadata) - not a proof of concept (see manifest.json's own
description and docs/CAMERA_ADAPTERS.md). Unlike BlackVueAdapter, this
isn't a delegation wrapper around existing code: ArchiveReader/
RecordingId.parse() both hard-assume BlackVue's flat "YYYYMMDD_HHMMSS_K"
filename convention (see recording_id.py), which a folder of ordinary
videos simply doesn't have. FolderAdapter instead:

- Walks `path` recursively (manifest.archive_layout == "recursive"),
  collecting every file whose extension is in
  manifest.video_extensions.
- Resolves each video's timestamp via ffprobe's embedded
  `format.tags.creation_time` first, falling back to the file's own
  mtime if that's missing, unparseable, or ffprobe itself fails -
  matching manifest.timestamp_source's declared order exactly.
- Synthesizes a RecordingId from that timestamp in the same
  "YYYYMMDD_HHMMSS_K" shape BlackVue ids already use (kind letter "V",
  the single code manifest.json's kind_vocabulary/direction_vocabulary
  both declare as primary) - deliberately reusing RecordingId as-is
  rather than inventing a parallel id type, so every existing
  RecordingId-based caller (bv-ls's --from/--until/--timestamp
  filters, TripBuilder's gap grouping, bv-web's URL routing) keeps
  working unchanged for a folder-adapter camera too. Two videos
  resolving to the same wall-clock second (rare, but possible for a
  folder of clips copied from multiple sources) are disambiguated by
  bumping the later one forward a second at a time until unique - an
  approximation, not a real ordering guarantee; see
  _assign_recording_ids()'s own docstring.
- Stores each video under Asset.FRONT - the single-video-per-recording
  equivalent of BlackVue's "front" camera, since direction_vocabulary
  here has exactly one code (also marked primary). This is what lets
  recordings_with_front_video() (bv-ls --trips, bv-export trip
  building), bv-ls's own "Front" column, and bv-web's archive
  browser/video player all keep working for folder recordings with no
  changes of their own - see manifest.json's unsupported_notes on why
  export is "a single-track passthrough" as a result.
- Looks for each of manifest.asset_suffix_table's 8 generated-asset
  suffixes as a same-stem sibling of the video file itself (e.g.
  "clip.mp4" + "clip.transcript.txt" in the same directory) - NOT
  keyed by the synthetic recording id the way BlackVue's ASSETS table
  is. A folder adapter's ids are computed at scan time and don't exist
  as a stable naming scheme anyone (a human, or a future bv-generate/
  bv-scribe run against this adapter) could target in advance; the
  video's own filename stem is the one stable, meaningful name
  available for this kind of archive.

STATUS: implemented and registered (see registry.py). Thumbnails
(capabilities.thumbnails == "generated") are NOT generated by this
module - the manifest's own thumbnail_generator code hook is still
queued; a recording with no thumbnail asset degrades the same way an
older/incomplete BlackVue archive already does throughout bv-web
(ArchiveRecording.thumbnail_direction returns None, the grid shows no
image for it) rather than blocking this pass on building that hook
too.
"""

from __future__ import annotations

import json
import subprocess
from datetime import datetime
from datetime import timedelta
from pathlib import Path

from ...archive.archive import Archive
from ...archive.asset import Asset
from ...archive.asset_file import AssetFile
from ...archive.configuration import Configuration
from ...archive.recording import Recording
from ...archive.recording_id import RecordingId
from ...core.endpoint import Endpoint
from ...telemetry.gps_reader import GpsFix
from ...telemetry.gsensor_reader import GSensorSample
from ..base import AdapterCapabilityError
from ..manifest import load_manifest

_MANIFEST_PATH = Path(__file__).parent / "manifest.json"
_MANIFEST = load_manifest(_MANIFEST_PATH)

# The single kind/direction code manifest.json's kind_vocabulary and
# direction_vocabulary both declare - see module docstring.
_KIND_CODE = "V"


def _probe_creation_time(path: Path) -> datetime | None:
    """Return a video's embedded `format.tags.creation_time` (ffprobe),
    or None if ffprobe is missing, fails, the tag isn't present, or the
    tag's value doesn't parse as an ISO-8601 timestamp - any of which
    just means "fall back to file mtime" to this adapter's caller, not
    an error worth surfacing on its own (a folder of ordinary videos
    routinely has some files with no creation_time metadata at all,
    e.g. after being re-encoded or copied through a tool that drops
    it)."""

    try:
        result = subprocess.run(
            [
                "ffprobe", "-v", "error",
                "-show_entries", "format_tags=creation_time",
                "-of", "json",
                str(path),
            ],
            capture_output=True,
            text=True,
            check=True,
        )
    except (FileNotFoundError, subprocess.CalledProcessError):
        return None

    try:
        tags = json.loads(result.stdout)["format"]["tags"]
        raw = tags["creation_time"]
    except (KeyError, ValueError, json.JSONDecodeError):
        return None

    # ffprobe reports creation_time as UTC ISO-8601, typically with a
    # trailing "Z" - datetime.fromisoformat() (3.11+) accepts that
    # directly, but this project's own minimum is broader, so normalize
    # "Z" to the explicit "+00:00" offset fromisoformat() has always
    # accepted.
    try:
        return datetime.fromisoformat(raw.replace("Z", "+00:00")).replace(tzinfo=None)
    except ValueError:
        return None


def _resolve_timestamp(path: Path) -> datetime:
    """Resolve a video's recording timestamp per
    manifest.timestamp_source's declared order: ffprobe's own
    creation_time metadata first, then the file's mtime - see
    _probe_creation_time()'s docstring for why the first step so
    often falls through to the second on a real, mixed-source folder
    of videos."""

    creation_time = _probe_creation_time(path)
    if creation_time is not None:
        return creation_time

    return datetime.fromtimestamp(path.stat().st_mtime)


def _scan_video_files(root: Path) -> list[Path]:
    """Recursively collect every file under `root` whose extension is
    one of manifest.video_extensions (archive_layout == "recursive") -
    sorted for deterministic, reproducible scan order (os.walk()'s own
    order is filesystem-dependent and not something callers, or this
    adapter's own collision-disambiguation in
    _assign_recording_ids(), should rely on)."""

    extensions = set(_MANIFEST.video_extensions)

    return sorted(
        path
        for path in root.rglob("*")
        if path.is_file() and path.suffix.lower() in extensions
    )


def _assign_recording_ids(
    videos: list[tuple[Path, datetime]],
) -> list[tuple[Path, RecordingId]]:
    """Turn (video path, resolved timestamp) pairs into (video path,
    RecordingId) pairs, one second apart at minimum.

    RecordingId's "YYYYMMDD_HHMMSS_K" shape only has one-second
    resolution, so two videos resolving to the same wall-clock second
    (two phones filming the same moment, clips copied from multiple
    sources into one folder) would otherwise collide and silently
    overwrite one another in the recordings dict. Ids are assigned in
    (already sorted) timestamp order, bumping any id that would repeat
    forward by one second until it's unique - an ordering
    approximation for the rare collision case, not a claim that the
    bumped second is when that clip actually happened.
    """

    assigned: list[tuple[Path, RecordingId]] = []
    seen: set[str] = set()

    for path, timestamp in sorted(videos, key=lambda item: (item[1], item[0])):
        candidate = timestamp
        value = f"{candidate:%Y%m%d_%H%M%S}_{_KIND_CODE}"
        while value in seen:
            candidate = candidate + timedelta(seconds=1)
            value = f"{candidate:%Y%m%d_%H%M%S}_{_KIND_CODE}"

        seen.add(value)
        assigned.append((path, RecordingId(value)))

    return assigned


def _generated_assets_for(video_path: Path) -> dict[Asset, AssetFile]:
    """Return every generated-asset sibling file that actually exists
    next to `video_path` - same-stem, per manifest.asset_suffix_table
    (see module docstring for why same-stem rather than recording-id
    -keyed)."""

    assets: dict[Asset, AssetFile] = {}
    stem_path = video_path.with_suffix("")

    for entry in _MANIFEST.asset_suffix_table:
        candidate = Path(str(stem_path) + entry.suffix)
        if candidate.is_file():
            asset = Asset[entry.asset]
            assets[asset] = AssetFile(asset=asset, path=candidate)

    return assets


class FolderArchive:
    """Archive-shaped container for a folder-adapter scan - see
    base.py's CameraAdapter.open_archive() docstring on duck-type
    compatibility: bv-ls/bv-web only ever touch `.recordings` and
    `.configuration(recording)`, both provided here without going
    through the BlackVue-specific Archive/ArchiveReader classes at
    all.

    `.configuration()` always returns Configuration.fallback() rather
    than looking for ".record_time.txt" snapshot files - this adapter
    's manifest declares config_snapshot support False (there's no
    config.ini equivalent for a folder of videos), so
    default_trip_gap_seconds (300s, matching the fallback's own
    record_time) is always the right answer here, not a degraded
    condition worth Archive's usual one-time warning about.
    """

    def __init__(self, recordings: list[Recording]):
        self._recordings = recordings
        self._fallback = Configuration.fallback()

    @property
    def recordings(self) -> list[Recording]:
        return self._recordings

    @property
    def configurations(self) -> list[Configuration]:
        return []

    def configuration(self, recording: Recording) -> Configuration:
        return self._fallback

    def __iter__(self):
        return iter(self._recordings)

    def __len__(self):
        return len(self._recordings)

    def __getitem__(self, index):
        return self._recordings[index]


def _scan(path: Path) -> list[Recording]:
    """Full recursive scan of `path`, returning Recording objects
    sorted by id - shared by open_archive() and find_recording()
    (which just filters this down to the one id it wants; see
    base.py's own docstring on why that's an accepted O(archive size)
    cost for this adapter)."""

    video_paths = _scan_video_files(path)
    videos_with_timestamps = [(p, _resolve_timestamp(p)) for p in video_paths]

    recordings = []
    for video_path, recording_id in _assign_recording_ids(videos_with_timestamps):
        assets: dict[Asset, AssetFile] = {
            Asset.FRONT: AssetFile(asset=Asset.FRONT, path=video_path),
        }
        assets.update(_generated_assets_for(video_path))

        size = 0
        for asset_file in assets.values():
            try:
                size += asset_file.path.stat().st_size
            except OSError:
                pass

        recordings.append(Recording(id=recording_id, assets=assets, size=size))

    return sorted(recordings, key=lambda r: r.id)


class FolderAdapter:
    """The "folder" CameraAdapter - see module docstring."""

    manifest = _MANIFEST

    def open_archive(self, path: Path) -> Archive:
        return FolderArchive(_scan(path))  # type: ignore[return-value]

    def find_recording(self, path: Path, recording_id: RecordingId) -> Recording | None:
        """Full rescan filtered by id - see base.py's own docstring on
        why this adapter has no equivalent to ArchiveReader's targeted,
        fixed-stat-count lookup: a folder adapter's ids are computed at
        scan time from resolved timestamps, not derivable from a
        filename alone the way a BlackVue id's own suffix-probing is."""

        for recording in _scan(path):
            if recording.id == recording_id:
                return recording
        return None

    def read_gps(self, path: Path) -> tuple[GpsFix, ...]:
        raise AdapterCapabilityError(
            f"{self.manifest.adapter_id} adapter's manifest does not "
            "declare gps support"
        )

    def read_gsensor(self, path: Path) -> tuple[GSensorSample, ...]:
        raise AdapterCapabilityError(
            f"{self.manifest.adapter_id} adapter's manifest does not "
            "declare gsensor support"
        )

    def connect(
        self, endpoints: list[Endpoint], timeout: int = 5
    ) -> tuple[Endpoint, object]:
        raise AdapterCapabilityError(
            f"{self.manifest.adapter_id} adapter's manifest does not "
            "declare network_connect support"
        )

    def config_snapshot_seconds(self, config_text: str) -> int:
        raise AdapterCapabilityError(
            f"{self.manifest.adapter_id} adapter's manifest does not "
            "declare config_snapshot support"
        )
